spring:
  application:
    name: order
  datasource:
    url: jdbc:postgresql://localhost:5432/order
    password: postgres
    username: postgres
  cloud:
    function:
      definition: payment;orderStatus;createClaim
    config:
      enable: true
    stream:
      kafka:
        default:
          producer.configuration.key.serializer: org.apache.kafka.common.serialization.StringSerializer
          consumer:
            enableDlq: false
            autoCommitOnError: true
            autoCommitOffset: true
        binder:
          brokers: localhost:9092
          minPartitionCount: 4
          autoAddPartitions: true
          consumerProperties:
            enable.auto.commit: true
            fetch.max.bytes: 62194560
            session.timeout.ms: 15000
          producerProperties:
            retries: 3
            batch.size: 16384
            buffer.memory: 33554432
            linger.ms: 1
      bindings:
        payment-in-0:
          destination: payment
          content-type: application/json
          group: order_group
        orderStatus-in-0:
          destination: order_status
          content-type: application/json
          group: order_group
        createClaim-out-0:
          destination: workflow-start-process
          content-type: application/json